# Tidak perlu "version:", ini sudah usang
services:
  prometheus:
    image: prom/prometheus:latest
    # Kita me-mount seluruh folder
    volumes:
      - ./prometheus_config:/etc/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: {}